
package br.com.fiap.financeira.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FinanceiroWebServiceService", targetNamespace = "http://servico.financeira.fiap.com.br/", wsdlLocation = "http://35.199.2.236:8080/InstituicaoFinanceira-1.0.0/FinanceiroWebService?wsdl")
public class FinanceiroWebServiceService
    extends Service
{

    private final static URL FINANCEIROWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FINANCEIROWEBSERVICESERVICE_EXCEPTION;
    private final static QName FINANCEIROWEBSERVICESERVICE_QNAME = new QName("http://servico.financeira.fiap.com.br/", "FinanceiroWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://35.199.2.236:8080/InstituicaoFinanceira-1.0.0/FinanceiroWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FINANCEIROWEBSERVICESERVICE_WSDL_LOCATION = url;
        FINANCEIROWEBSERVICESERVICE_EXCEPTION = e;
    }

    public FinanceiroWebServiceService() {
        super(__getWsdlLocation(), FINANCEIROWEBSERVICESERVICE_QNAME);
    }

    public FinanceiroWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINANCEIROWEBSERVICESERVICE_QNAME, features);
    }

    public FinanceiroWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, FINANCEIROWEBSERVICESERVICE_QNAME);
    }

    public FinanceiroWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINANCEIROWEBSERVICESERVICE_QNAME, features);
    }

    public FinanceiroWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinanceiroWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FinanceiroWebService
     */
    @WebEndpoint(name = "FinanceiroWebServicePort")
    public FinanceiroWebService getFinanceiroWebServicePort() {
        return super.getPort(new QName("http://servico.financeira.fiap.com.br/", "FinanceiroWebServicePort"), FinanceiroWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinanceiroWebService
     */
    @WebEndpoint(name = "FinanceiroWebServicePort")
    public FinanceiroWebService getFinanceiroWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.financeira.fiap.com.br/", "FinanceiroWebServicePort"), FinanceiroWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINANCEIROWEBSERVICESERVICE_EXCEPTION!= null) {
            throw FINANCEIROWEBSERVICESERVICE_EXCEPTION;
        }
        return FINANCEIROWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
